[program:roxabi-intel]
command=%(ENV_HOME)s/projects/roxabi-intel/run.sh
directory=%(ENV_HOME)s/projects/roxabi-intel
environment=HOME="%(ENV_HOME)s",INTEL_DIR="%(ENV_HOME)s/roxabi/intel",INTEL_PORT="8082"
autostart=false
autorestart=true
startsecs=3
startretries=3
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=%(ENV_HOME)s/.local/state/roxabi-intel/logs/roxabi-intel.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile=%(ENV_HOME)s/.local/state/roxabi-intel/logs/roxabi-intel_error.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=3
